parameters:
#    constancia.example.class: Frontend\ConstanciaBundle\Example

services:
#    constancia.example:
#        class: %constancia.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
