parameters:
#    directorio.example.class: Frontend\DirectorioBundle\Example

services:
#    directorio.example:
#        class: %directorio.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
