parameters:
#    cumpleanios.example.class: Frontend\CumpleaniosBundle\Example

services:
#    cumpleanios.example:
#        class: %cumpleanios.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
