proyecto_homepage:
    path:     /index
    defaults: { _controller: ProyectoBundle:Default:index }

ProyectoBundle_proyecto:
    resource: "@ProyectoBundle/Resources/config/routing/proyecto.yml"
    prefix:   /proyecto

ProyectoBundle_tarea:
    resource: "@ProyectoBundle/Resources/config/routing/tarea.yml"
    prefix:   /tarea

ProyectoBundle_actividad:
    resource: "@ProyectoBundle/Resources/config/routing/actividad.yml"
    prefix:   /actividad

ProyectoBundle_comentarioactividad:
    resource: "@ProyectoBundle/Resources/config/routing/comentarioactividad.yml"
    prefix:   /comentarioactividad

