parameters:
#    incidencia.example.class: Frontend\IncidenciaBundle\Example

services:
#    incidencia.example:
#        class: %incidencia.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
