parameters:
#    licencias.example.class: Frontend\LicenciasBundle\Example

services:
#    licencias.example:
#        class: %licencias.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
