<?php

namespace Frontend\TransporteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AsignacionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignacionesRepository extends EntityRepository
{
}
