comentarioactividad:
    path:     /lista/{idactividad}
    defaults: { _controller: "ProyectoBundle:Comentarioactividad:index" }

comentarioactividad_show:
    path:     /{id}/show
    defaults: { _controller: "ProyectoBundle:Comentarioactividad:show" }

comentarioactividad_new:
    path:     /new/{idactividad}
    defaults: { _controller: "ProyectoBundle:Comentarioactividad:new" }

comentarioactividad_create:
    path:     /create/{idactividad}
    defaults: { _controller: "ProyectoBundle:Comentarioactividad:create" }
    requirements: { _method: post }

comentarioactividad_edit:
    path:     /edit/{id}
    defaults: { _controller: "ProyectoBundle:Comentarioactividad:edit" }

comentarioactividad_update:
    path:     /{id}/update
    defaults: { _controller: "ProyectoBundle:Comentarioactividad:update" }
    requirements: { _method: post|put }

comentarioactividad_delete:
    path:     /{id}/delete
    defaults: { _controller: "ProyectoBundle:Comentarioactividad:delete" }
    requirements: { _method: post|delete }
