parameters:
#    videoteca.example.class: Frontend\VideotecaBundle\Example

services:
#    videoteca.example:
#        class: %videoteca.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
