proyecto:
    resource: "@ProyectoBundle/Resources/config/routing.yml"
    prefix:   /proyecto

creatv:
    resource: "@CreatvBundle/Resources/config/routing.yml"
    prefix:   /creatv

transporte:
    resource: "@TransporteBundle/Resources/config/routing.yml"
    prefix:   /transporte

#vehiculos_index:
#    resource: "@TransporteBundle/Resources/config/routing/vehiculos.yml"
#    prefix:   /transporte/vehiculos

#solicitudes_index:
#    resource: "@TransporteBundle/Resources/config/routing/solicitudes.yml"
#    prefix:   /transporte/solicitudes   

#personalexterno_index:
#        resource: "@TransporteBundle/Resources/config/routing/personalexterno.yml"
#        prefix:   /transporte/personalexterno

#TransporteBundle_asignaciones:
#        resource: "@TransporteBundle/Resources/config/routing/asignaciones.yml"
#        prefix:   /transporte/asignaciones


cumpleanios:
    resource: "@CumpleaniosBundle/Resources/config/routing.yml"
    prefix:   /cumpleanios

incidencia:
    resource: "@IncidenciaBundle/Resources/config/routing.yml"
    prefix:   /

mercal:
    resource: "@MercalBundle/Resources/config/routing.yml"
    prefix:   /jornada
directorio:
    resource: "@DirectorioBundle/Resources/config/routing.yml"
    prefix:   /directorio
contratos:
    resource: "@ContratosBundle/Resources/config/routing.yml"
    prefix:   /contratos

contenidos:
    resource: "@ContenidosBundle/Resources/config/routing.yml"
    prefix:   /contenidos

sit:
    resource: "@SitBundle/Resources/config/routing.yml"
    prefix:   /sit

constancia:
    resource: "@ConstanciaBundle/Resources/config/routing.yml"
    prefix:   /constancia

neto:
    resource: "@NetoBundle/Resources/config/routing.yml"
    prefix:   /neto

nomina:
    resource: "@NominaBundle/Resources/config/routing.yml"
    prefix:   /nomina

licencias:
    resource: "@LicenciasBundle/Resources/config/routing.yml"
    prefix:   /licencias

frontend_visitas:
    resource: "@FrontendVisitasBundle/Resources/config/routing.yml"
    prefix:   /usuario_control

distribucion:
    resource: "@DistribucionBundle/Resources/config/routing.yml"
    prefix:   /distribucion

videoteca:
    resource: "@VideotecaBundle/Resources/config/routing.yml"
    prefix:   /videoteca

usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /usuario

login:
    pattern:  /
    defaults: { _controller: UsuarioBundle:Default:index }

visitas:
    resource: "@FrontendVisitasBundle/Resources/config/routing.yml"
    prefix:   /visitas
