security:
    firewalls:
        frontend:
            pattern: ^/
            anonymous: true
            form_login:
                login_path: /usuario/login
                check_path: /usuario/login_check
                default_target_path: /usuario/inicio
                always_use_default_target_path: true
            logout:
                path: usuario_logout
                target: /usuario/login


            
    providers:
        usuarios:
            entity: { class: Administracion\UsuarioBundle\Entity\User, property: username }
        
    encoders:
        Administracion\UsuarioBundle\Entity\User:
            algorithm: 'md5'
            iterations: 1
            encode_as_base64: false

        #Symfony\Component\Security\Core\User\User: plaintext

    access_control:
        - { path: ^/usuario/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/usuario, roles: ROLE_ADMINISTRADOR }
        - { path: ^/usuario/rol, roles: ROLE_ADMINISTRADOR }

        - { path: ^/distribucion, roles: ROLE_DISTRIBUCION }
        - { path: ^/distribucion/ajax, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/distribucion/ajax_top, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path:  ^/licencias/reportes, roles:[ROLE_LICENCIAS , ROLE_LICADMIN] }
        - { path: ^/licencias/modif, roles:ROLE_LICADMIN }
