security:
    firewalls:
        frontend:
            pattern: ^/
            anonymous: true
            form_login:
                login_path: /usuario/login
                check_path: /usuario/login_check
                default_target_path: /usuario/inicio
                always_use_default_target_path: true
            logout:
                path: usuario_logout
                target: /usuario/login


            
    providers:
        usuarios:
            entity: { class: Administracion\UsuarioBundle\Entity\User, property: username }
        
    encoders:
       # Administracion\UsuarioBundle\Entity\User: { algorithm: plaintext }

        Administracion\UsuarioBundle\Entity\User: 
            algorithm: md5
            iterations:       0
            encode_as_base64: false

        #Symfony\Component\Security\Core\User\User: plaintext

    access_control:
        - { path: ^/usuario/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/notificar, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/inicio, roles: ROLE_USER }
        - { path: ^/usuario/contacto, roles: ROLE_USER }
        - { path: ^/usuario/cambioclave, roles: ROLE_USER }
        - { path: ^/usuario, roles: ROLE_ADMINISTRADOR }

        - { path: ^/distribucion/operador/new, roles: ROLE_DISTRIBUCION_ADMINISTRADOR }
        - { path: ^/distribucion/operador/edit, roles: ROLE_DISTRIBUCION_ADMINISTRADOR }
        - { path: ^/distribucion/tipooperador/new, roles: ROLE_DISTRIBUCION_ADMINISTRADOR }
        - { path: ^/distribucion/tipooperador/edit, roles: ROLE_DISTRIBUCION_ADMINISTRADOR }
        - { path: ^/distribucion/representante/newAdd, roles: ROLE_DISTRIBUCION_ADMINISTRADOR }
        - { path: ^/distribucion/representante/edit, roles: ROLE_DISTRIBUCION_ADMINISTRADOR }
        - { path: ^/distribucion/objetocomodato/new, roles: ROLE_DISTRIBUCION_ADMINISTRADOR }
        - { path: ^/distribucion/objetocomodato/edit, roles: ROLE_DISTRIBUCION_ADMINISTRADOR }
        - { path: ^/distribucion/zona/new, roles: ROLE_DISTRIBUCION_ADMINISTRADOR }
        - { path: ^/distribucion/zona/edit, roles: ROLE_DISTRIBUCION_ADMINISTRADOR }
        - { path: ^/distribucion, roles: ROLE_DISTRIBUCION }

        - { path: ^/constancia/inicio, roles: ROLE_CONSTANCIA_ADMINISTRADOR}
        - { path: ^/constancia/edit, roles: ROLE_CONSTANCIA_ADMINISTRADOR}
        - { path: ^/constancia, roles: ROLE_USER}

        
        - { path: ^/sit/inicio, roles: ROLE_USER}
        - { path: ^/sit/ticket/create, roles: ROLE_USER}
        - { path: ^/sit/ticketgeneral, roles: ROLE_SIT_GENERAL}
        - { path: ^/sit/listausuariounidad, roles: ROLE_SIT_SUPERADMINISTRADOR}
        - { path: ^/sit/ticket, roles: ROLE_SIT_ADMINISTRADOR}
        - { path: ^/sit/asignado, roles: ROLE_SIT_ADMINISTRADOR}
        - { path: ^/sit/categoria, roles: ROLE_SIT_ADMINISTRADOR}
        - { path: ^/sit/subcategoria, roles: ROLE_SIT_ADMINISTRADOR}

        - { path:  ^/licencias/reportes, roles:[ROLE_LICENCIAS , ROLE_LICADMIN] }
        - { path: ^/licencias/modif, roles:ROLE_LICADMIN }

        - { path: ^/contenidos, roles:ROLE_CONTENIDOS }

        - { path: ^/neto, roles: ROLE_USER }

        - { path: ^/visita, roles: ROLE_VISITAS }

        - { path: ^/jornada/numeracion, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/jornada/homepagenum, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/jornada/ajaxmercalsiguienteautomatico, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/jornada/homepagejor, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/jornada/homepagenum, roles: IS_AUTHENTICATED_ANONYMOUSLY}


        

        - { path: ^/jornada/jornada, roles: ROLE_JORNADA}
        - { path: ^/jornada/asignum, roles: ROLE_JORNADA_ASIGNUM}
        - { path: ^/jornada/num, roles: ROLE_JORNADA_NUM}
        
        - { path: ^/jornada, roles: ROLE_USER}

