security:
    firewalls:
        frontend:
            pattern: ^/
            anonymous: true
            form_login:
                login_path: /usuario/login
                check_path: /usuario/login_check
                default_target_path: /usuario/inicio
                always_use_default_target_path: true
            logout:
                path: usuario_logout
                target: /usuario/login


            
    providers:
        usuarios:
            entity: { class: Administracion\UsuarioBundle\Entity\User, property: username }
        
    encoders:
       # Administracion\UsuarioBundle\Entity\User: { algorithm: plaintext }

        Administracion\UsuarioBundle\Entity\User: 
            algorithm: md5
            iterations:       0
            encode_as_base64: false

        #Symfony\Component\Security\Core\User\User: plaintext

    access_control:
        - { path: ^/usuario/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/inicio, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/contacto, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/distribucion/operador/new, roles: ROLE_DISTRIBUCION_ADMINISTRADOR }
        - { path: ^/distribucion/operador/edit, roles: ROLE_DISTRIBUCION_ADMINISTRADOR }
        - { path: ^/distribucion/tipooperador/new, roles: ROLE_DISTRIBUCION_ADMINISTRADOR }
        - { path: ^/distribucion/tipooperador/edit, roles: ROLE_DISTRIBUCION_ADMINISTRADOR }
        - { path: ^/distribucion/representante/newAdd, roles: ROLE_DISTRIBUCION_ADMINISTRADOR }
        - { path: ^/distribucion/representante/edit, roles: ROLE_DISTRIBUCION_ADMINISTRADOR }
        - { path: ^/distribucion/objetocomodato/new, roles: ROLE_DISTRIBUCION_ADMINISTRADOR }
        - { path: ^/distribucion/objetocomodato/edit, roles: ROLE_DISTRIBUCION_ADMINISTRADOR }
        - { path: ^/distribucion/zona/new, roles: ROLE_DISTRIBUCION_ADMINISTRADOR }
        - { path: ^/distribucion/zona/edit, roles: ROLE_DISTRIBUCION_ADMINISTRADOR }
        - { path: ^/distribucion, roles: ROLE_DISTRIBUCION }


        - { path: ^/usuario, roles: ROLE_ADMINISTRADOR }

        - { path: ^/constancia/inicio, roles: ROLE_CONSTANCIA_ADMINISTRADOR}
        - { path: ^/constancia/edit, roles: ROLE_CONSTANCIA_ADMINISTRADOR}


        - { path:  ^/licencias/reportes, roles:[ROLE_LICENCIAS , ROLE_LICADMIN] }
        - { path: ^/licencias/modif, roles:ROLE_LICADMIN }

        - { path: ^/contenidos, roles:ROLE_CONTENIDOS }
