parameters:
#    distribucion.example.class: Frontend\DistribucionBundle\Example

services:
#    distribucion.example:
#        class: %distribucion.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
