constancia:
    pattern:  /
    defaults: { _controller: "ConstanciaBundle:Constancia:index" }

constancia_show:
    pattern:  /{id}/show
    defaults: { _controller: "ConstanciaBundle:Constancia:show" }

constancia_new:
    pattern:  /new
    defaults: { _controller: "ConstanciaBundle:Constancia:new" }

constancia_create:
    pattern:  /create
    defaults: { _controller: "ConstanciaBundle:Constancia:create" }
    requirements: { _method: post }

constancia_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ConstanciaBundle:Constancia:edit" }

constancia_update:
    pattern:  /{id}/update
    defaults: { _controller: "ConstanciaBundle:Constancia:update" }
    requirements: { _method: post|put }

constancia_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ConstanciaBundle:Constancia:delete" }
    requirements: { _method: post|delete }
