parameters:
#    transporte.example.class: Frontend\TransporteBundle\Example

services:
#    transporte.example:
#        class: %transporte.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
