sit_homepage:
    pattern:  /inicio
    defaults: { _controller: SitBundle:Default:index }

# TICKETS #


ticket_asignado:
    pattern:  /asignado
    defaults: { _controller: "SitBundle:Ticket:asignado" }

ticket_showasignado:
    pattern:  /{id}/showasignado
    defaults: { _controller: "SitBundle:Ticket:showasignado" }

ticket_asignadosolucion:
    pattern:  /{id}/asignadosolucion
    defaults: { _controller: "SitBundle:Ticket:asignadosolucion" }

ticket:
    pattern:  /ticket
    defaults: { _controller: "SitBundle:Ticket:index" }


ticket_show:
    pattern:  /{id}/show
    defaults: { _controller: "SitBundle:Ticket:show" }


ticket_asigreasig:
    pattern:  /asigreasig/{id}
    defaults: { _controller: "SitBundle:Ticket:asigreasig" }

ticket_listausuariounidad:
    pattern:  /listausuariounidad
    defaults: { _controller: "SitBundle:Ticket:listausuariounidad" }

ticket_usuariounidad:
    pattern:  /usuariounidad/{id}
    defaults: { _controller: "SitBundle:Ticket:usuariounidad" }

ticket_asignarusuariounidad:
    pattern:  /asignarusuariounidad/{id}
    defaults: { _controller: "SitBundle:Ticket:asignarusuariounidad" }

ticket_asignarcatsub:
    pattern:  /{id}/catsub
    defaults: { _controller: "SitBundle:Ticket:catsub" }

ticket_guardacatsub:
    pattern:  /{id}/guardacatsub
    defaults: { _controller: "SitBundle:Ticket:guardacatsub" }

ticket_new:
    pattern:  /ticket/new
    defaults: { _controller: "SitBundle:Ticket:new" }

ticket_create:
    pattern:  /ticket/create
    defaults: { _controller: "SitBundle:Ticket:create" }
    requirements: { _method: post }

ticket_edit:
    pattern:  /ticket/edit/{id}
    defaults: { _controller: "SitBundle:Ticket:edit" }

ticket_update:
    pattern:  /ticket/update/{id}
    defaults: { _controller: "SitBundle:Ticket:update" }
    requirements: { _method: post|put }

ticket_delete:
    pattern:  /ticket/delete/{id}
    defaults: { _controller: "SitBundle:Ticket:delete" }
    requirements: { _method: post|delete }

# FIN TICKET #


# CATEGORIA #
categoria:
    pattern:  /categoria
    defaults: { _controller: "SitBundle:Categoria:index" }

categoria_show:
    pattern:  /categoria/{id}/show
    defaults: { _controller: "SitBundle:Categoria:show" }

categoria_new:
    pattern:  /categoria/new
    defaults: { _controller: "SitBundle:Categoria:new" }

categoria_create:
    pattern:  /categoria/create
    defaults: { _controller: "SitBundle:Categoria:create" }
    requirements: { _method: post }

categoria_edit:
    pattern:  /categoria/{id}/edit
    defaults: { _controller: "SitBundle:Categoria:edit" }

categoria_update:
    pattern:  /categoria/{id}/update
    defaults: { _controller: "SitBundle:Categoria:update" }
    requirements: { _method: post|put }

categoria_delete:
    pattern:  /categoria/{id}/delete
    defaults: { _controller: "SitBundle:Categoria:delete" }
    requirements: { _method: post|delete }

# FIN CATEGORIA #

# SUBCATEGORIA #
subcategoria:
    pattern:  /subcategoria/{id}
    defaults: { _controller: "SitBundle:Subcategoria:index" }

subcategoria_show:
    pattern:  /subcategoria/{id}/show
    defaults: { _controller: "SitBundle:Subcategoria:show" }

subcategoria_new:
    pattern:  /subcategoria/new/{id}
    defaults: { _controller: "SitBundle:Subcategoria:new" }

subcategoria_create:
    pattern:  /subcategoria/create/{id}
    defaults: { _controller: "SitBundle:Subcategoria:create" }
    requirements: { _method: post }

subcategoria_edit:
    pattern:  /subcategoria/edit/{idsub}/{idcat}
    defaults: { _controller: "SitBundle:Subcategoria:edit" }

subcategoria_update:
    pattern:  /subcategoria/update/{idsub}/{idcat}
    defaults: { _controller: "SitBundle:Subcategoria:update" }
    requirements: { _method: post|put }

subcategoria_delete:
    pattern:  /subcategoria/{id}/delete
    defaults: { _controller: "SitBundle:Subcategoria:delete" }
    requirements: { _method: post|delete }


# FIN SUBCATEGORIA #

# REPORTE #
reporte:
    pattern:  /reporte
    defaults: { _controller: "SitBundle:Reporte:index" }

reporte_ajaxinformegestion:
    pattern:  /ajaxinformegestion/{datos}/{mostrar}
    defaults: { _controller: "SitBundle:Ajax:ajaxinformegestion" }

reporte_generarinforme:
    pattern:  /generarinforme
    defaults: { _controller: "SitBundle:Reporte:generarinforme" }