parameters:
#    contratos.example.class: Frontend\ContratosBundle\Example

services:
#    contratos.example:
#        class: %contratos.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
