mercal_homepagejor:
    pattern:  /homepagejor
    defaults: { _controller: MercalBundle:Default:homepagejor }

mercal_homepagenum:
    pattern:  /homepagenum/{idjornada}
    defaults: { _controller: MercalBundle:Default:homepagenum }

ajaxmercal_siguienteautomatico:
    pattern:  /ajaxmercalsiguienteautomatico/{idjornada}
    defaults: { _controller: MercalBundle:Ajax:ajaxmercalsiguienteautomatico }


mercal_homepage:
    pattern:  /numeracion/{idjornada}
    defaults: { _controller: MercalBundle:Default:index }

mercal_cerrarjornada:
    pattern:  /cerrarjornada/{idjornada}
    defaults: { _controller: MercalBundle:Ajax:cerrarjornada }

mercal_jornadanumeracion:
    pattern:  /jornadanumeracion
    defaults: { _controller: MercalBundle:Default:jornadanumeracion }

ajaxmercal_siguiente:
    pattern:  /ajaxmercalsiguiente/{valor}/{idjornada}/{usernumeroid}/{compro}
    defaults: { _controller: MercalBundle:Ajax:ajaxmercalsiguiente }

ajaxmercal_siguientecomprobar:
    pattern:  /ajaxmercalsiguientecomprobar/{idjornada}
    defaults: { _controller: MercalBundle:Ajax:ajaxmercalsiguientecomprobar }

mercal_seleccionajornada:
    pattern:  /seleccionajornada
    defaults: { _controller: MercalBundle:Default:seleccionajornada }


mercal_listado:
    pattern:  /listado/{idjornada}
    defaults: { _controller: MercalBundle:Default:listado }

mercal_listadofam:
    pattern:  /listadofam/{idtrabajador}/{idjornada}
    defaults: { _controller: MercalBundle:Default:listadofam }

mercal_asignarnumero:
    pattern:  /asignarnumero/{idtrabajador}/{idjornada}
    defaults: { _controller: MercalBundle:Default:asignarnumero }

mercal_eliminarnumerotrab:
    pattern:  /eliminarnumerotrab/{idtrabajador}/{idjornada}
    defaults: { _controller: MercalBundle:Default:eliminarnumerotrab }

mercal_eliminarnumerofam:
    pattern:  /eliminarnumerofam/{idtrabajador}/{idfamiliar}/{idjornada}
    defaults: { _controller: MercalBundle:Default:eliminarnumerofam }

mercal_guardaasignarnumero:
    pattern:  /guardaasignarnumero/{idtrabajador}/{idjornada}
    defaults: { _controller: MercalBundle:Default:guardaasignarnumero }

mercal_nuevofam:
    pattern:  /nuevofam/{idtrabajador}/{idjornada}
    defaults: { _controller: MercalBundle:Default:nuevofam }

mercal_guardanuevofam:
    pattern:  /guardanuevofam/{idtrabajador}/{idjornada}
    defaults: { _controller: MercalBundle:Default:guardanuevofam }

mercal_guardaasignarnumerofam:
    pattern:  /guardaasignarnumerofam/{idtrabajador}/{idfamiliar}/{idjornada}
    defaults: { _controller: MercalBundle:Default:guardaasignarnumerofam }

mercal_editarfam:
    pattern:  /editarfam/{idfamiliar}/{idjornada}
    defaults: { _controller: MercalBundle:Default:editarfam }

mercal_actualizaeditarfam:
    pattern:  /actualizaeditarfam/{idfamiliar}/{idjornada}
    defaults: { _controller: MercalBundle:Default:actualizaeditarfam }


mercal_borrarfam:
    pattern:  /borrarfam/{idtrabajador}/{idfamiliar}/{idjornada}
    defaults: { _controller: MercalBundle:Default:borrarfam }



jornada:
    pattern:  /jornada/lista
    defaults: { _controller: "MercalBundle:Jornada:index" }

jornada_show:
    pattern:  /{id}/show
    defaults: { _controller: "MercalBundle:Jornada:show" }

jornada_new:
    pattern:  /new
    defaults: { _controller: "MercalBundle:Jornada:new" }

jornada_create:
    pattern:  /create
    defaults: { _controller: "MercalBundle:Jornada:create" }
    requirements: { _method: post }

jornada_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "MercalBundle:Jornada:edit" }

jornada_update:
    pattern:  /{id}/update
    defaults: { _controller: "MercalBundle:Jornada:update" }
    requirements: { _method: post|put }

jornada_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "MercalBundle:Jornada:delete" }
    requirements: { _method: post|delete }
