CREATE TABLE tipoproducto (
	id int PRIMARY KEY,
	nombre VARCHAR(255)
);
INSERT INTO "tipoproducto" VALUES(1,'CELL PHONE');
INSERT INTO "tipoproducto" VALUES(2,'LAPTOP');
INSERT INTO "tipoproducto" VALUES(3,'MONITOR');
INSERT INTO "tipoproducto" VALUES(4,'KEYBOARD');
INSERT INTO "tipoproducto" VALUES(5,'MOUSE');
INSERT INTO "tipoproducto" VALUES(6,'CPU');

CREATE TABLE productos (
	id INT PRIMARY KEY,
	tipoproducto_id INT,
	modelo VARCHAR(50),
	costo DOUBLE PRECISION,
	FOREIGN KEY (tipoproducto_id) REFERENCES tipoproducto (id)
);
INSERT INTO "productos" VALUES(1,1,'GALAXY SPICA',1500);
INSERT INTO "productos" VALUES(2,1,'HTC MAGIC',1300);
INSERT INTO "productos" VALUES(3,1,'GOOGLE NEXUS ONE',5400);
INSERT INTO "productos" VALUES(4,2,'LENOVO T61',2500);
INSERT INTO "productos" VALUES(5,2,'ALIENWARE',15000);
INSERT INTO "productos" VALUES(6,2,'HP',5000);
INSERT INTO "productos" VALUES(7,2,'VIT',4800);
INSERT INTO "productos" VALUES(8,3,'PANASONIC',4800);
INSERT INTO "productos" VALUES(9,3,'SAMSUNG',1800);
INSERT INTO "productos" VALUES(10,3,'HP',2200);
INSERT INTO "productos" VALUES(11,4,'HP',200);
INSERT INTO "productos" VALUES(12,4,'LENOVO',200);
INSERT INTO "productos" VALUES(13,4,'VIT',200);
INSERT INTO "productos" VALUES(14,5,'INALAMBRICO',200);
INSERT INTO "productos" VALUES(15,5,'456DS',200);
INSERT INTO "productos" VALUES(16,5,'DHGW',60);
INSERT INTO "productos" VALUES(17,5,'54DWE',60);
INSERT INTO "productos" VALUES(18,6,'INTEL',600);
INSERT INTO "productos" VALUES(19,6,'AMD',650);
INSERT INTO "productos" VALUES(20,6,'MOTOROLA',450);