##########################################################################################################
#                                                 PROVEEDOR
##########################################################################################################
datosproveedor:
    pattern:  /proveedor/home
    defaults: { _controller: "ContenidosBundle:Datosproveedor:index" }
datoscompras:
    pattern: /compras/home
    defaults: { _controller: "ContenidosBundle:Datosproveedor:compras"}
datosinformacion:
    pattern: /informacio&nacute;n/home
    defaults: { _controller: "ContenidosBundle:Datosproveedor:informacion" }
datosequipos:
    pattern: /equipostelesur/home
    defaults: { _controller: "ContenidosBundle:Datosproveedor:equipos"}
datossatelites:
    pattern: /satelites/home
    defaults: { _controller: "ContenidosBundle:Datosproveedor:satelites"}

datosproveedor_show:
    pattern:  /proveedor/detalles/{id}
    defaults: { _controller: "ContenidosBundle:Datosproveedor:show" }

datosproveedor_new:
    pattern:  /proveedor/nuevo
    defaults: { _controller: "ContenidosBundle:Datosproveedor:new" }

datosproveedor_create:
    pattern:  /proveedor/crear
    defaults: { _controller: "ContenidosBundle:Datosproveedor:create" }
    requirements: { _method: post }

datosproveedor_edit:
    pattern:  /proveedor/editar/{id}
    defaults: { _controller: "ContenidosBundle:Datosproveedor:edit" }

datosproveedor_update:
    pattern:  /proveedor/actualizar/{id}
    defaults: { _controller: "ContenidosBundle:Datosproveedor:update" }
    requirements: { _method: post|put }

datosproveedor_delete:
    pattern:  /proveedor/eliminar/{id}
    defaults: { _controller: "ContenidosBundle:Datosproveedor:delete" }
    requirements: { _method: post|delete }


##########################################################################################################
#                                          TIPO DE PROVEEDOR
##########################################################################################################
tipoproveedor:
    pattern:  tipoproveedor/home
    defaults: { _controller: "ContenidosBundle:Tipoproveedor:index" }

tipoproveedor_show:
    pattern:  tipoproveedor/detalles/{id}
    defaults: { _controller: "ContenidosBundle:Tipoproveedor:show" }

tipoproveedor_new:
    pattern:  tipoproveedor/nuevo
    defaults: { _controller: "ContenidosBundle:Tipoproveedor:new" }

tipoproveedor_create:
    pattern:  tipoproveedor/crear
    defaults: { _controller: "ContenidosBundle:Tipoproveedor:create" }
    requirements: { _method: post }

tipoproveedor_edit:
    pattern:  tipoproveedor/editar/{id}
    defaults: { _controller: "ContenidosBundle:Tipoproveedor:edit" }

tipoproveedor_update:
    pattern:  tipoproveedor/actualizar/{id}
    defaults: { _controller: "ContenidosBundle:Tipoproveedor:update" }
    requirements: { _method: post|put }

tipoproveedor_delete:
    pattern:  tipoproveedor/eliminar/{id}
    defaults: { _controller: "ContenidosBundle:Tipoproveedor:delete" }
    requirements: { _method: post|delete }


##########################################################################################################
#                                                 BANCO
##########################################################################################################
banco:
    pattern:  banco/home
    defaults: { _controller: "ContenidosBundle:Banco:index" }

banco_show:
    pattern:  banco/detalles/{id}
    defaults: { _controller: "ContenidosBundle:Banco:show" }

banco_new:
    pattern:  banco/nuevo
    defaults: { _controller: "ContenidosBundle:Banco:new" }

banco_create:
    pattern:  banco/crear
    defaults: { _controller: "ContenidosBundle:Banco:create" }
    requirements: { _method: post }

banco_edit:
    pattern:  banco/editar/{id}
    defaults: { _controller: "ContenidosBundle:Banco:edit" }

banco_update:
    pattern:  banco/actualizar/{id}
    defaults: { _controller: "ContenidosBundle:Banco:update" }
    requirements: { _method: post|put }

banco_delete:
    pattern:  banco/eliminar/{id}
    defaults: { _controller: "ContenidosBundle:Banco:delete" }
    requirements: { _method: post|delete }


##########################################################################################################
#                                             CONTRATACION
##########################################################################################################
contratacion:
    pattern:  contratacion/home
    defaults: { _controller: "ContenidosBundle:Contratacion:index" }

contratacion_show:
    pattern:  contratacion/detalles/{id}
    defaults: { _controller: "ContenidosBundle:Contratacion:show" }

contratacion_new:
    pattern:  contratacion/nuevo
    defaults: { _controller: "ContenidosBundle:Contratacion:new" }

contratacion_create:
    pattern:  contratacion/crear
    defaults: { _controller: "ContenidosBundle:Contratacion:create" }
    requirements: { _method: post }

contratacion_edit:
    pattern:  contratacion/editar/{id}
    defaults: { _controller: "ContenidosBundle:Contratacion:edit" }

contratacion_update:
    pattern:  contratacion/actualizar/{id}
    defaults: { _controller: "ContenidosBundle:Contratacion:update" }
    requirements: { _method: post|put }

contratacion_delete:
    pattern:  contratacion/eliminar/{id}
    defaults: { _controller: "ContenidosBundle:Contratacion:delete" }
    requirements: { _method: post|delete }


##########################################################################################################
#                                                   PAGO
##########################################################################################################
pago:
    pattern:  /pago/home/{id_proveedor}
    defaults: { _controller: "ContenidosBundle:Pago:index" }

pago_show:
    pattern:  pago/detalles/{id}/{id_proveedor}
    defaults: { _controller: "ContenidosBundle:Pago:show" }

pago_new:
    pattern:  pago/nuevo/{id_proveedor}
    defaults: { _controller: "ContenidosBundle:Pago:new" }

pago_create:
    pattern:  pago/crear/{id_proveedor}
    defaults: { _controller: "ContenidosBundle:Pago:create" }
    requirements: { _method: post }

pago_edit:
    pattern:  pago/editar/{id}/{id_proveedor}
    defaults: { _controller: "ContenidosBundle:Pago:edit" }

pago_update:
    pattern:  pago/actualizar/{id}
    defaults: { _controller: "ContenidosBundle:Pago:update" }
    requirements: { _method: post|put }

pago_delete:
    pattern:  pago/eliminar/{id}
    defaults: { _controller: "ContenidosBundle:Pago:delete" }
    requirements: { _method: post|delete }


##########################################################################################################
#                                            CONTROL DEL PAGO
##########################################################################################################
controlpagounidad:
    pattern:  controlpagounidad/home
    defaults: { _controller: "ContenidosBundle:Controlpagounidad:index" }

controlpagounidad_show:
    pattern:  controlpagounidad/detalles/{id}
    defaults: { _controller: "ContenidosBundle:Controlpagounidad:show" }

controlpagounidad_new:
    pattern:  controlpagounidad/nuevo
    defaults: { _controller: "ContenidosBundle:Controlpagounidad:new" }

controlpagounidad_create:
    pattern:  controlpagounidad/crear
    defaults: { _controller: "ContenidosBundle:Controlpagounidad:create" }
    requirements: { _method: post }

controlpagounidad_edit:
    pattern:  controlpagounidad/editar/{id}
    defaults: { _controller: "ContenidosBundle:Controlpagounidad:edit" }

controlpagounidad_update:
    pattern:  controlpagounidad/actualizar/{id}
    defaults: { _controller: "ContenidosBundle:Controlpagounidad:update" }
    requirements: { _method: post|put }

controlpagounidad_delete:
    pattern:  controlpagounidad/eliminar/{id}
    defaults: { _controller: "ContenidosBundle:Controlpagounidad:delete" }
    requirements: { _method: post|delete }


##########################################################################################################
#                                            PRESUPUESTO
##########################################################################################################
presupuesto:
    pattern:  /presupuesto/home
    defaults: { _controller: "ContenidosBundle:Presupuesto:index" }

presupuesto_show:
    pattern:  presupuesto/detalles/{id}
    defaults: { _controller: "ContenidosBundle:Presupuesto:show" }

presupuesto_new:
    pattern:  presupuesto/nuevo
    defaults: { _controller: "ContenidosBundle:Presupuesto:new" }

presupuesto_create:
    pattern:  presupuesto/crear
    defaults: { _controller: "ContenidosBundle:Presupuesto:create" }
    requirements: { _method: post }

presupuesto_edit:
    pattern:  presupuesto/editar/{id}
    defaults: { _controller: "ContenidosBundle:Presupuesto:edit" }

presupuesto_update:
    pattern:  presupuesto/actualizar/{id}
    defaults: { _controller: "ContenidosBundle:Presupuesto:update" }
    requirements: { _method: post|put }

presupuesto_delete:
    pattern:  presupuesto/eliminar/{id}
    defaults: { _controller: "ContenidosBundle:Presupuesto:delete" }
    requirements: { _method: post|delete }


##########################################################################################################
#                                               OTRAS
##########################################################################################################
ajax_datosproveedor:
    pattern: /ajax/contenidos/{datos}
    defaults: { _controller: "ContenidosBundle:Ajax:datosproveedor"}
