parameters:
#    contenidos.example.class: Frontend\ContenidosBundle\Example

services:
#    contenidos.example:
#        class: %contenidos.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
