<?php

namespace Proxies\__CG__\Frontend\ProyectoBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Tarea extends \Frontend\ProyectoBundle\Entity\Tarea implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setEstatus($estatus)
    {
        $this->__load();
        return parent::setEstatus($estatus);
    }

    public function getEstatus()
    {
        $this->__load();
        return parent::getEstatus();
    }

    public function setDescripcion($descripcion)
    {
        $this->__load();
        return parent::setDescripcion($descripcion);
    }

    public function getDescripcion()
    {
        $this->__load();
        return parent::getDescripcion();
    }

    public function setFechainicio($fechainicio)
    {
        $this->__load();
        return parent::setFechainicio($fechainicio);
    }

    public function getFechainicio()
    {
        $this->__load();
        return parent::getFechainicio();
    }

    public function setFechafinreal($fechafinreal)
    {
        $this->__load();
        return parent::setFechafinreal($fechafinreal);
    }

    public function getFechafinreal()
    {
        $this->__load();
        return parent::getFechafinreal();
    }

    public function setFechafinestimada($fechafinestimada)
    {
        $this->__load();
        return parent::setFechafinestimada($fechafinestimada);
    }

    public function getFechafinestimada()
    {
        $this->__load();
        return parent::getFechafinestimada();
    }

    public function setPorcentaje($porcentaje)
    {
        $this->__load();
        return parent::setPorcentaje($porcentaje);
    }

    public function getPorcentaje()
    {
        $this->__load();
        return parent::getPorcentaje();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setProyecto(\Frontend\ProyectoBundle\Entity\Proyecto $proyecto = NULL)
    {
        $this->__load();
        return parent::setProyecto($proyecto);
    }

    public function getProyecto()
    {
        $this->__load();
        return parent::getProyecto();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'estatus', 'nombre', 'descripcion', 'fechainicio', 'fechafinestimada', 'fechafinreal', 'porcentaje', 'proyecto');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}