parameters:
#    frontend_agenda.example.class: Frontend\AgendaBundle\Example

services:
#    frontend_agenda.example:
#        class: %frontend_agenda.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
