parameters:
#    creatv.example.class: Frontend\CreatvBundle\Example

services:
#    creatv.example:
#        class: %creatv.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
