ticket:
    pattern:  /
    defaults: { _controller: "SitBundle:Ticket:index" }

ticket_show:
    pattern:  /{id}/show
    defaults: { _controller: "SitBundle:Ticket:show" }

ticket_new:
    pattern:  /new
    defaults: { _controller: "SitBundle:Ticket:new" }

ticket_create:
    pattern:  /create
    defaults: { _controller: "SitBundle:Ticket:create" }
    requirements: { _method: post }

ticket_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "SitBundle:Ticket:edit" }

ticket_update:
    pattern:  /{id}/update
    defaults: { _controller: "SitBundle:Ticket:update" }
    requirements: { _method: post|put }

ticket_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "SitBundle:Ticket:delete" }
    requirements: { _method: post|delete }
